#! /bin/sh

sxhkd &
~/.config/lemonbar/start &
~/.fehbg &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12
bspc config focused_border_color \#892825

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs state=tiled
